site_name: CommX Wiki (Knowledge Base)
theme:
    name: material
    palette:
        - scheme: default
          primary: custom
          accent: custom
        - scheme: slate
          primary: custom
          accent: custom
extra_css:
    - stylesheets/extra.css
plugins:
    - search

nav:
    - Home: index.md
    - General Info: 00-general/index.md
    - Services: 10-services/index.md
    - "User's Guide": 20-userguide/index.md
    - Development Guidelines: 30-development/index.md
    - Integration Guidelines: 40-integration/index.md
    - "Extra: Issues, Links, FAQ": 50-extra/index.md
    - Migration from Old UAS:
          - Overview: 60-migration/index.md
          - Old UAS Services: 60-migration/old-services-status.md
          - Old UAS Settings: 60-migration/old-uas-settings-revision.md

markdown_extensions:
    - tables
    - attr_list
    - admonition
